### ISSUE TITLE
delimiters no longer supported?

### ISSUE THREAD

**Issue by erzz** [jaywcjlove/github-action-contributors#25]
According to the docs we should be able to specify the delimiters (I want this to be able to reuse the action multiple times)

But I dont see these inputs in action.yml any more?

![image](https://github.com/jaywcjlove/github-action-contributors/assets/58994586/b4627496-3d70-474f-8f6c-1a3b03df810e)

**Comment by jaywcjlove** [comment]
@erzz 

👉 https://github.com/jaywcjlove/github-action-modify-file-content

**Comment by jaywcjlove** [comment]
@erzz `github-action-contributors` generates an SVG string, which is modified into the specified text file using `github-action-modify-file-content`.
